# First install and load devtools
install.packages("devtools", repos="http://cran.rstudio.com/")
library(devtools)

# Install epidatr from GitHub
install_github("cmu-delphi/epidatr", ref="main")
install_github("cmu-delphi/epidatasets", ref="main")
install_github("cmu-delphi/epipredict", ref="main")
install_github("cmu-delphi/epiprocess", ref="main")

# Install the rest of your packages
install.packages(c("anytime", "askpass", "backports", "base64enc", "bayestestR", "BH", "bit", "bit64", "blob", "brew", "broom", "bslib", "cachem", "callr", "cellranger", "checkmate", "cli", "clipr", "clock", "collections", "colorspace", "commonmark", "conflicted", "correlation", "cpp11", "crayon", "credentials", "curl", "cyclocomp", "data.table", "datawizard", "DBI", "dbplyr", "desc", "diagram", "dials", "DiceDesign", "diffobj", "digest", "distributional", "doFuture", "dplyr", "dtplyr", "effectsize", "ellipsis", "evaluate", "fansi", "farver", "fastmap", "fontawesome", "forcats", "foreach", "fs", "furrr", "future", "future.apply", "gargle", "generics", "genlasso", "gert", "ggplot2", "gh", "gitcreds", "globals", "glue", "googledrive", "googlesheets4", "gower", "GPfit", "gtable", "hardhat", "haven", "highr", "hms", "htmltools", "httr", "httr2", "ids", "igraph", "infer", "ini", "insight", "ipred", "isoband", "iterators", "jquerylib", "jsonlite", "knitr", "labeling", "languageserver", "lava", "lazyeval", "lhs", "lifecycle", "lintr", "listenv", "lubridate", "magrittr", "memoise", "mime", "MMWRweek", "modelbased", "modeldata", "modelenv", "modelr", "munsell", "numDeriv", "openssl", "pak", "parallelly", "parameters", "parsnip", "patchwork", "performance", "pillar", "pkgbuild", "pkgconfig", "pkgload", "poissonreg", "prettyunits", "processx", "prodlim", "progress", "progressr", "ps", "purrr", "R.cache", "R.methodsS3", "R.oo", "R.utils", "R6", "ragg", "ranger", "rappdirs", "RColorBrewer", "Rcpp", "RcppEigen", "RcppRoll", "readr", "readxl", "recipes", "rematch", "rematch2", "remotes", "reprex", "rex", "rlang", "rmarkdown", "roxygen2", "rprojroot", "rsample", "rstudioapi", "rvest", "sass", "scales", "see", "selectr", "sessioninfo", "sfd", "shape", "slider", "SQUAREM", "stringi", "stringr", "styler", "sys", "systemfonts", "textshaping", "tibble", "tidymodels", "tidyr", "tidyselect", "tidyverse", "timechange", "timeDate", "tinytex", "tsibble", "tune", "tzdb", "usethis", "utf8", "uuid", "vctrs", "viridisLite", "vroom", "waldo", "warp", "whisker", "withr", "workflows", "workflowsets", "xfun", "xgboost", "xml2", "xmlparsedata", "yaml", "yardstick", "zip", "base", "boot", "class", "cli", "cluster", "codetools", "compiler", "datasets", "foreign", "glue", "graphics", "grDevices", "grid", "KernSmooth", "lattice", "magrittr", "markdown", "MASS", "Matrix", "methods", "mgcv", "mime", "nlme", "nnet", "parallel", "rlang", "rpart", "spatial", "splines", "stats", "stats4", "stringi", "survival", "tcltk", "tools", "utils", "vctrs", "xfun", "yaml", "evaluate", "highr", "knitr", "lifecycle", "stringr"))
